#This file stores configuration options for Iris, such as the currently active shaderpack
#Sat Sep 13 17:09:56 EDT 2025
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
maxShadowRenderDistance=32
shaderPack=ComplementaryReimagined_r5.4
enableShaders=false
